version: 1.1
kind: operation
name: build-dash
params:
  destination:
    connection: CONNECTION_NAME
    value: polyaxon-examples:dash-demo
  context:
    value: "{{ globals.artifacts_path }}/dash-polyaxon-demo"
runPatch:
  init:
    - git:
        url: "https://github.com/polyaxon/dash-polyaxon-demo"
hubRef: kaniko
